obj-$(CONFIG_EXTENDED_LSM) := seccomp.o 
obj-$(CONFIG_SECURITY_AZURE_SPHERE) := udom.o main.o fl_list.o fl_netlink.o fl_iface.o difc_fs.o helper.o checker_fs.o
EXTRA_CFLAGS += -Isecurity/s_module/include


